<a href="https://colab.research.google.com/github/danieljcoh/DC_SpringBoard_Notes/blob/main/Beginning_With_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working with CSVs

- When we use the `read_csv()` metho,d it returns a DataFrame.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')

- `head()` will give us the first 5 rows and all columns.

In [3]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

`tail()` will give us the last 5 rows and all columns.

In [4]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

## From a Ditionary to a DataFrame

In [11]:
affinities = {
    1: ["Alex Strider", "Fire", "Blonde", "Blue", "Male"],
    2: ["Luna Eclipse", "Water", "Black", "Silver", "Female"],
    3: ["Terra Forge", "Earth", "Brown", "Green", "Non-binary"],
    4: ["Zane Volt", "Electric", "Black", "Yellow", "Male"],
    5: ["Iris Ember", "Plasma", "Red", "Amber", "Female"],
    6: ["Kai Tempest", "Wind", "White", "Blue", "Male"],
    7: ["Nia Shadow", "Dark", "Purple", "Black", "Female"],
    8: ["Solar Nova", "Light", "Golden", "White", "Non-binary"],
    9: ["Astra Quill", "Ice", "Blue", "Gray", "Female"],
    10: ["Drake Pyro", "Fire", "Orange", "Red", "Male"],
    11: ["Mira Wave", "Water", "Blue", "Sea Green", "Female"],
    12: ["Geo Core", "Earth", "Brown", "Brown", "Male"],
    13: ["Bolt Flash", "Electric", "Yellow", "Bright Yellow", "Non-binary"],
    14: ["Blaze Vega", "Plasma", "Crimson", "Orange", "Female"],
    15: ["Skye Gale", "Wind", "Gray", "Sky Blue", "Male"],
    16: ["Eclipse Void", "Dark", "Black", "Crimson", "Non-binary"],
    17: ["Aurora Ray", "Light", "Platinum", "Golden", "Female"],
    18: ["Frost Glimmer", "Ice", "Silver", "Icy Blue", "Male"],
    19: ["Inferno Ash", "Fire", "Black", "Scarlet", "Male"],
    20: ["Zephyr Drift", "Wind", "Blonde", "Gray", "Female"]
}

dict_df = pd.DataFrame.from_dict(affinities)

In [8]:
dict_df.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,Alex Strider,Luna Eclipse,Terra Forge,Zane Volt,Iris Ember,Kai Tempest,Nia Shadow,Solar Nova,Astra Quill,Drake Pyro,Mira Wave,Geo Core,Bolt Flash,Blaze Vega,Skye Gale,Eclipse Void,Aurora Ray,Frost Glimmer,Inferno Ash,Zephyr Drift
1,Fire,Water,Earth,Electric,Plasma,Wind,Dark,Light,Ice,Fire,Water,Earth,Electric,Plasma,Wind,Dark,Light,Ice,Fire,Wind
2,Blonde,Black,Brown,Black,Red,White,Purple,Golden,Blue,Orange,Blue,Brown,Yellow,Crimson,Gray,Black,Platinum,Silver,Black,Blonde
3,Blue,Silver,Green,Yellow,Amber,Blue,Black,White,Gray,Red,Sea Green,Brown,Bright Yellow,Orange,Sky Blue,Crimson,Golden,Icy Blue,Scarlet,Gray
4,Male,Female,Non-binary,Male,Female,Male,Female,Non-binary,Female,Male,Female,Male,Non-binary,Female,Male,Non-binary,Female,Male,Male,Female

In [12]:
dict_df.tail()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,Alex Strider,Luna Eclipse,Terra Forge,Zane Volt,Iris Ember,Kai Tempest,Nia Shadow,Solar Nova,Astra Quill,Drake Pyro,Mira Wave,Geo Core,Bolt Flash,Blaze Vega,Skye Gale,Eclipse Void,Aurora Ray,Frost Glimmer,Inferno Ash,Zephyr Drift
1,Fire,Water,Earth,Electric,Plasma,Wind,Dark,Light,Ice,Fire,Water,Earth,Electric,Plasma,Wind,Dark,Light,Ice,Fire,Wind
2,Blonde,Black,Brown,Black,Red,White,Purple,Golden,Blue,Orange,Blue,Brown,Yellow,Crimson,Gray,Black,Platinum,Silver,Black,Blonde
3,Blue,Silver,Green,Yellow,Amber,Blue,Black,White,Gray,Red,Sea Green,Brown,Bright Yellow,Orange,Sky Blue,Crimson,Golden,Icy Blue,Scarlet,Gray
4,Male,Female,Non-binary,Male,Female,Male,Female,Non-binary,Female,Male,Female,Male,Non-binary,Female,Male,Non-binary,Female,Male,Male,Female

## DataFrame Attributes

### Columns

In [10]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

- For DataFrames made from Dictionaries, the columns would be the `keys` of the `key:value` pair

In [13]:
dict_df.columns

Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], dtype='int64')

### DTypes

In [14]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [15]:
dict_df.dtypes

1     object
2     object
3     object
4     object
5     object
6     object
7     object
8     object
9     object
10    object
11    object
12    object
13    object
14    object
15    object
16    object
17    object
18    object
19    object
20    object
dtype: object

## Summary Statistics

### Describe

- Using the `describe()` method, we can calculate automatically certain mathematical functions such as...
- count
- mean
- standard deviation
- min
- etc...

** An Important Note!**

- The `describe()` method will only be called on the data that are Integers or Floats

In [18]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

- However, we can **specify** the type of data we want to describe

In [20]:
# The type of data in the dictionary dataframe was all objects as we can see from earlier
dict_df.describe(include="object")

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
count,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
unique,5,5,5,5,5,5,5,5,5,5,5,4,5,5,5,5,5,5,5,5
top,Alex Strider,Luna Eclipse,Terra Forge,Zane Volt,Iris Ember,Kai Tempest,Nia Shadow,Solar Nova,Astra Quill,Drake Pyro,Mira Wave,Brown,Bolt Flash,Blaze Vega,Skye Gale,Eclipse Void,Aurora Ray,Frost Glimmer,Inferno Ash,Zephyr Drift
freq,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1

# Filtering for specific data

### Getting a single column

- We can use two different ways.
- We can use the column similar to an attribute but this could get confusing.
- We can access the column by the name of the column similar to accessing a key's value in a python dictionary

In [21]:
df.population

0       1537.0
1        809.0
2       1484.0
3         49.0
4        850.0
         ...
2995    1258.0
2996    3496.0
2997     693.0
2998      46.0
2999     753.0
Name: population, Length: 3000, dtype: float64

In [22]:
df["population"]

0       1537.0
1        809.0
2       1484.0
3         49.0
4        850.0
         ...
2995    1258.0
2996    3496.0
2997     693.0
2998      46.0
2999     753.0
Name: population, Length: 3000, dtype: float64

## Getting Two Columns Data

- We can access multiple columns by using an array

In [25]:
df[["longitude", "latitude"]]

      longitude  latitude
0       -122.05     37.37
1       -118.30     34.26
2       -117.81     33.78
3       -118.36     33.82
4       -119.67     36.33
...         ...       ...
2995    -119.86     34.42
2996    -118.14     34.06
2997    -119.70     36.30
2998    -117.12     34.10
2999    -119.63     34.42

[3000 rows x 2 columns]

## Filtering for specific Rows

- Like if the median age of housing is greater than a certain age.

In [28]:
df[df["housing_median_age"] > 25.0]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
...,...,...,...,...,...,...,...,...,...
2993,-117.91,33.60,37.0,2088.0,510.0,673.0,390.0,5.1048,500001.0
2994,-117.93,33.86,35.0,931.0,181.0,516.0,174.0,5.5867,182500.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

### Filtering for specific data in multiple rows

In [34]:
df[(df["housing_median_age"] > 25.0) & (df["population"] > 4500.0)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
122,-118.21,33.92,28.0,2949.0,1003.0,4551.0,930.0,1.9026,131900.0
171,-119.18,34.19,36.0,4519.0,1081.0,4818.0,1061.0,2.8561,179100.0
2321,-121.15,38.69,52.0,240.0,44.0,6675.0,29.0,6.1359,225000.0

# Using `iloc()`

- `iloc()` allows us to filter through our data using integers instead of labels or text

- This means: In our df, DataFrame, go to the "4th" row (because it's 0 indexed) and print out that entire row.
- This will include all the labels and data pieces for a singular row of data

In [36]:
df.iloc[3]

longitude               -118.3600
latitude                  33.8200
housing_median_age        28.0000
total_rooms               67.0000
total_bedrooms            15.0000
population                49.0000
households                11.0000
median_income              6.1359
median_house_value    330000.0000
Name: 3, dtype: float64

- We can specify further even just singular piece of data from that row.
- This could mean, everything from the "4th" row but only the 1st column, which depending on our data labels in the columns, would only print out one piece of data corresponding to a singular data row

In [41]:
print("latitude: " + str(df.iloc[3, 1]))
print("housing_median_age: " + str(df.iloc[3, 2]))

latitude: 33.82
housing_median_age: 28.0

### Slicing our DataFrame

- We can slice data from rows to consolidate specific data we are looking to retrieve
- Here we sliced just rows 10 and 11
- As you can see the slicing command is **exclusive**

In [42]:
df.iloc[10:12]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
10,-118.24,33.98,45.0,972.0,249.0,1288.0,261.0,2.2054,125000.0
11,-119.12,35.85,37.0,736.0,166.0,564.0,138.0,2.4167,58300.0

# Using the `loc()` method -- WIP

- the difference between `loc` and `iloc` is that `loc` is label based and `iloc` is integer based.

- First we need to index our DataFrame by giving our rows a labeled index that we can call to access the data in the rows

In [43]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

# Dropping Rows

In [44]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

- We can drop specific columns
- Axis = 1 here tells the computer we are dropping a column not a row

In [47]:
df.drop("longitude", axis=1)

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...
2995,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

## Creating a Column

In [48]:
df["New Col"] = df["longitude"] + df["longitude"]

- As you can see, "New Col" is added to the end of the data columns

In [49]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New Col
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,-244.10
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,-236.60
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,-235.62
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,-236.72
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,-239.34

## Updating Values in a column

- We are saying here, using the first row data line and index of the column at -1 and set that cell to 10

In [50]:
df.iloc[0, -1] = 10

In [51]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New Col
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,10.00
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,-236.60
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,-235.62
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,-236.72
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,-239.34

## Using `apply()`

- Here we are going to make a new column to the DataFrame but we are doing so for every row of data by using the `apply()` method and taking the data from "total_bedrooms" and see if it meets a certain criteria
- The lambda function here lets us apply a certain criteria to each piece of data in the new cell based on the old data from "total_bedrooms"

In [52]:
df["Happiness"] = df["total_bedrooms"].apply(lambda x: x > 500)

In [53]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New Col,Happiness
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,10.00,True
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,-236.60,False
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,-235.62,True
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,-236.72,False
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,-239.34,False